//
//  trump_test_02.c
//  prg202X
//
//  Created by x22004xx on 2022/04/21.
//

#include <stdio.h>
#include <unistd.h>

int main(int argc, const char *argv[]){
    //idや名前等2ちゃんねる風のテンプレート引用元:https://www.pixiv.net/novel/show.php?id=901945 //
    printf("1：風と木の名無しさん　2022/04/20 16:29:54　ID：MnHAJBzWMy\n");
    printf("　　　　 　　／⌒ヽ\n");
    printf("⊂二二二（　＾ω＾）二⊃\n");
    printf("　　　　　　|　　　 / 　　　　　　ﾌﾞｰﾝ\n");
    printf("　　 　　　 （　ヽノ\n");
    printf("　　　　　　 ﾉ>ノ\n");
    printf("　　 三　　レﾚ\n\n\n\n\n");
    sleep(2);
//以後時間の許す限り何かしら作る//
    printf("2：風と木の名無しさん　2022/04/23 11:39:24　ID：P6zvnYGvy!\n");
    int i;
    for(i=0; i<10; i++)
    printf ("(」・ω・)」うー!\r");
    fflush(stdout);
    sleep(1);
    printf("\r(/・ω・)/にゃ\r");
    fflush(stdout);
    sleep(1);
    printf("(」・ω・)」うー!\r");
    fflush(stdout);
    sleep(1);
    printf("\r(/・ω・)/にゃー!\r");
    fflush(stdout);
    sleep(1);
    printf("(」・ω・)」うー!\r");
    fflush(stdout);
    sleep(1);
    printf("\r(/・ω・)/にゃー!\r");
    fflush(stdout);
    sleep(1);
    printf("(」・ω・)」うー!\r");
    fflush(stdout);
    sleep(1);
    printf("\r(/・ω・)/にゃー!\n\n\n\n\n");
    fflush(stdout);
    sleep(2);
    //上記のコードの参考にしたサイト:http://shouginekochann.blog9.fc2.com/blog-entry-213.html?sp
// //サイト2:https://daeudaeu.com/fflush/ //
    printf("3 名前：風と木の名無しさん 2022/04/23 18:19:43　ID：9cfoH^Dj2i\n");
    printf("ゲーミングAIT\n");
    printf(" \x1b[31m█████  ██ ████████\x1b[0m \n");
    printf("\x1b[33m██   ██ ██    ██\x1b[0m \n");
    printf("\x1b[32m███████ ██    ██\x1b[0m \n");
    printf("\x1b[36m██   ██ ██    ██\x1b[0m \n");
    printf("\x1b[34m██   ██ ██    ██\x1b[0m\n\n\n\n\n");
    sleep(2);
    printf("4 名前：風と木の名無しさん 2022/04/25 15:29:54　ID：JOAXlnZGAE\n");
    printf("殺伐としたソースコードにトランプが！！\n\n\n");
    printf("qNNNNNNNNmQQmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmQQQQQQNNNNNNNN[\n");
    printf("MMMMMMMMH9=<~````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````_?TWMMMMMMMMP\n");
    printf("MMMMMHY!`                                                                                                                                                                         ?THMMMMP\n");
    printf("MMMMD!                                                                                                                                                                              ?WMMMP\n");
    printf("MMH3                                                                                                                                                                                  7MMP\n");
    printf("MM$                                                                                                                                                                                    OMP\n");
    printf("WD`                                                                                                                                                                                    .H$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                     \x1b[31m(,\x1b[0m                                                                                                                                                               d$\n");
    printf("X$`                  \x1b[31m.jf}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$                 \x1b[31m`.zzf}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$                 \x1b[31m.v~(f}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$                \x1b[31m.v` (f}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$`             \x1b[31m`.?`  (f}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$              \x1b[31m(<`   (f}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$             \x1b[31m(>`    (f}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$             \x1b[31m?777777TfY77!\x1b[0m                                                                                                                                                            d$\n");
    printf("X$`                   \x1b[31m(f}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$                    \x1b[31m(f}\x1b[0m                                                                                                                                                               d$\n");
    printf("X$                 \x1b[31m.(+ZU0+(.\x1b[0m                                                                                                                                                            d$\n");
    printf("X$`                                                                                                                                                                                     d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                            \x1b[31m.JuXkkA&-.       ..+wkkkA+..                                          ..+wkkkA-.        .JwkkkA&-.\x1b[0m                                        d$\n");
    printf("X$                                         \x1b[31m.(dfppfpfpffk&.    (dffpffpfffk+.                                      .dWffpfpfffWn.    .dfpfppfpffko.\x1b[0m                                      d$\n");
    printf("X$`                                       \x1b[31m.dpfffffffffffWn- .jfffffffffpffpk-                                   .jXfffffffpffffk<  (Xffffffffpffpkx\x1b[0m                                     d$\n");
    printf("X$                                       \x1b[31m.dfffpffpfpfpfpfWy.Jffpfpfpfpffpfffk-                                  jWfpfpfpfffpffffk-(Xffpffpffpfffffk{\x1b[0m                                    d$\n");
    printf("X$               \x1b[31m..(--.      .((--.      .fffpffpfffpfffpfWwffpfffpfffpfffffW>                                 .dpffffpfpfffpfpffkdffpffpffpffpfpffI\x1b[0m                                    d$\n");
    printf("X$             \x1b[31m.dXpfpfWk+  .dWpfffWA-.   (ffpffffpffffpffffffpffpfffpffpfpfpWI                                 (dffpfffffpfffpfpfpffpfffffpffffpffp$_\x1b[0m                                   d$\n");
    printf("X$`           \x1b[31m(XfffffpffW>(dfffpffffWo.  .WffpfpffpffpffpfpffffpffpffpffffpfS!                                  dWffpfpffpfpffffpffpffpffpffpffffpW3\x1b[0m                                    d$\n");
    printf("X$            \x1b[31mdfpffpffpffWWfffpffpfpfW_   (WffpffffpfffpfffpfpfffpffffpffffW>                                   -ZWffpffpfffpfffffpffffpfffpfpfpfW$\x1b[0m                                     d$\n");
    printf("X$            \x1b[31mjffpffpfffpfffpfffpffff0`    (Ufffpfffpfffpfffpffpfffpfffpfp0>                                     -vWfffpfffffpfpfffpfpffpfffffpfW$\x1b[0m                                      d$\n");
    printf("X$`           \x1b[31m.zWfpffpfffpfffpfffpfp0!      _wWpfpfffpfffpffffpffpffpffffV!                                        ?Wpfffpfpffffpfffpffffpfpfff0=\x1b[0m                                       d$\n");
    printf("X$              \x1b[31m?WffffpfffpfffpfffWC`         zWffpfffpfffpfpfffpffpffpfY!                                          ?Wpfffpffpffpfpfffpfffpfpf0!\x1b[0m                                        d$\n");
    printf("X$               \x1b[31m?Xfpffpfffpfffpf0>            ?Xffpffpfpffffpffffpffp0C`                                            (TfffffpffpfffpffpfpffffV`\x1b[0m                                         d$\n");
    printf("X$                 \x1b[31m?WffpfpffpffWV!              _VffpffffpffpffpffffW0!                                                jWpffffpfffffpffffpfX>`\x1b[0m                                          d$\n");
    printf("X$`                 \x1b[31m?Uffffpffp0=                  ?WffpfffpfffpfpfpW$`                                                  ?XfpfffpfpfffpffpfV!\x1b[0m                                            d$\n");
    printf("X$                    \x1b[31mjWfffpW0!                    (Uffpfffpfffffp0>                                                     _vWfpffffpfffpfW$`\x1b[0m                                             d$\n");
    printf("X$                     \x1b[31m?WffWC`                      .zWfpfffpfpff0!                                                        ?WffpffpfpffSC\x1b[0m                                               d$\n");
    printf("X$                      \x1b[31m(4WC`                         ?WfpfffpffC`                                                          (UffpffffW0!\x1b[0m                                                d$\n");
    printf("X$`                      \x1b[31m(!                            (XfpfffX>`                                                            .OffpfpWC`\x1b[0m                                                 d$\n");
    printf("X$                                                      \x1b[31m_dfpf0>                                                                jWffWC`\x1b[0m                                                  d$\n");
    printf("X$                                                        \x1b[31mwfS>                                                                  jWWC`\x1b[0m                                                   d$\n");
    printf("X$`                                                       \x1b[31m.VC                                                                    jC`\x1b[0m                                                    d$\n");
    printf("X$                                                         \x1b[31m`\x1b[0m                                                                                                                            d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                        \x1b[31m` `                                                                    `\x1b[0m                                                      d$\n");
    printf("X$`                                                        \x1b[31m-.                                                                   `.-\x1b[0m                                                     d$\n");
    printf("X$                                                        \x1b[31m.Xo                                                                   .dn_\x1b[0m                                                    d$\n");
    printf("X$                                                       \x1b[31m.dfWl.                                                               `.jffn_\x1b[0m                                                   d$\n");
    printf("X$                                                      \x1b[31m(dfffWl.                                                              .dfffpA-`\x1b[0m                                                 d$\n");
    printf("X$`                                                  \x1b[31m` (Xffpfffn.                                                          ` .Xffpffpk-                         ` .y.\x1b[0m                   d$\n");
    printf("X$                                                   \x1b[31m.jWpfpffpfpk-                                                          (Xffffpfffk+                         .dfk.\x1b[0m                  d$\n");
    printf("X$                                                  \x1b[31m.dfffpffffpffk+                                                      `.jWfpfpffffpfWo.                      (Xfffk-\x1b[0m                 d$\n");
    printf("X$                                               \x1b[31m` (XfpffffpffffpfWo.                                                    .dpfffpffpffffffk-                   .jWfpfffko.\x1b[0m               d$\n");
    printf("X$`                                              \x1b[31m.dffffpffpfpffpffpfk,                                                `.(Xffpffffpfpfpffffk+.                (dffpfpffffA-\x1b[0m              d$\n");
    printf("X$                                            \x1b[31m` (wffpfffpffffpfffpffpWx.                                              .dfffffpffpfffffpfpffWo-             .jfffffffpffpfk+.\x1b[0m            d$\n");
    printf("X$                                            \x1b[31m.jXffffpfffpffpffpffffffWn-                                            .Xffpfpffpfffpffpffpffpfk-           .XffpfpffpffpfffWw-`\x1b[0m          d$\n");
    printf("X$`                                          \x1b[31m.dWffpffpfpffpfffpffpfpfpfpk-                                        `.+ffpffpffffpfffpfffpffpfffk&       `.+Wffffpffpfffffpffpk+`\x1b[0m         d$\n");
    printf("X$                                          \x1b[31m(dfffffpffffpfffpfffpfffpffffWi.                                    ` .dffpffffpfpffpfffpffffpffpffWs.     .dffffpfffpffpffpfffffWo\x1b[0m         d$\n");
    printf("X$                                         \x1b[31m(Xfffpfffpffpfffpffpfffpfffpffffo.                                   `.dffffpfpffffpffpfffpffpffffpfffn.   `jWfffpffpfffpffpffpffffk>\x1b[0m        d$\n");
    printf("X$                                        \x1b[31m(WffpffpfffpfffpfffpffpffpfffpffpWo                                   .dfpfpffffpffpffffpfffpffpfpfffpffn-   dWfpfffpffpWUffffpfpfpfk:\x1b[0m        d$\n");
    printf("X$`                                      \x1b[31m.XffpffpffpffpfffpffffpffffpfffpfffW<`                                .dfffpffpfffpfffpffpfpfffffpffpfffpWI   _Xfffpffff0> Offpfffff0C\x1b[0m         d$\n");
    printf("X$                                       \x1b[31m(ffpfffffpffffpfffpffpffpfffpfffpffWI                                 (dfffffpfpfffpfffpffffpfpffffpfffpff$~    ?TUWfWUY!   ?UWffWUY!\x1b[0m          d$\n");
    printf("X$                                       \x1b[31m.fpffpffpffpfffpfkzWfffpfpffpfpffpfW>                                 (dfpfpffffpfffpffWCdfffpfpfpfffpffffr        ```         ```\x1b[0m             d$\n");
    printf("X$                                        \x1b[31mOffffpfffpfpfffW3 (ffpfffpffffpffW0`                                  ?Wfffpffpffpffpf$`(XfpfffffpfffpfpS>\x1b[0m                                    d$\n");
    printf("X$`                                        \x1b[31mjWfffpfffffpfWC   jWfffffpffpffWY`                                    ?WpffpfffpfffWf!  ?XffpffpffpffWf!\x1b[0m                                     d$\n");
    printf("X$                                          \x1b[31m_7WffpfpffWY!     (TWfpffpffWY!                                        ?UfffpfffW0>     _?WffpffffWV^`\x1b[0m                                      d$\n");
    printf("X$                                             \x1b[31m??7T77?`          ?77777!                                             _?77T77!          ?77T77?`\x1b[0m                                         d$\n");
    printf("X$`                                                                                                                                                            \x1b[31m??WHf<?`\x1b[0m                 d$\n");
    printf("X$                                                                                                                                                               \x1b[31mdW>\x1b[0m                    d$\n");
    printf("X$                                                                                                                                                               \x1b[31mdW>\x1b[0m                    d$\n");
    printf("X$                                                                                                                                                            \x1b[31m(11XW011111zz\x1b[0m             d$\n");
    printf("X$`                                                                                                                                                              \x1b[31mzW>    .J!\x1b[0m             d$\n");
    printf("X$                                                                                                                                                               \x1b[31mdW>   .J!\x1b[0m              d$\n");
    printf("X$                                                                                                                                                               \x1b[31mdW>  .x!\x1b[0m               d$\n");
    printf("X$                                                                                                                                                               \x1b[31mdW> .v!\x1b[0m                d$\n");
    printf("X$`                                                                                                                                                              \x1b[31mdW>.2`\x1b[0m                 d$\n");
    printf("X$                                                                                                                                                               \x1b[31mdWy3\x1b[0m                   d$\n");
    printf("X$                                                                                                                                                               \x1b[31mdWC\x1b[0m                    d$\n");
    printf("X$`                                                                                                                                                              \x1b[31m_!\x1b[0m                     d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("X$                                                                                                                                                                                      d$\n");
    printf("XS                                                                                                                                                                                      d$\n");
    printf("WH-                                                                                                                                                                                    .Wr\n");
    printf("MNR                                                                                                                                                                                   .dMP\n");
    printf("MMNn.                                                                                                                                                                                .dMMP\n");
    printf("MMMNH&.                                                                                                                                                                            .(WMMMP\n");
    printf("MMMMNNk&..`                                                                                                                                                                    ` .+WNMMMMP\n");
    printf("MMMMMMMNNHm&--...............................................................................................................................................................(+gHNMMMMMMMP\n");
    printf("7\"\"\"\"\"\"\"\"\"\"\"\"77777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777\"\"\"\"\"\"\"\"\"\"\"7\n");
    //エスケープシーケンスがうまく動作しない、要調査////追記:ダブルクォーテーションの位置に注意、左から右に、上から下に流れて反応する//
    return 0;
}
